import * as dotenv from 'dotenv'
dotenv.config()

const {
  SUPERLIKERS_URL,
  VERYFI_VALIDATE_URL,
  VERYFI_BASE_URL,

  TENA_VERIFY_API_KEY,
  TENA_VERYFI_CLIENT_ID,
  TENA_VERYFI_CLIENT_SECRET,
  TENA_VERYFI_USERNAME,
  TENA_API_KEY,
  TENA_CAMPAIGN_ID,

  SABA_VERIFY_CLIENT_ID,
  SABA_VERIFY_CLIENT_SECRET,
  SABA_VERIFY_USERNAME,
  SABA_VERIFY_API_KEY,
  SABA_CAMPAIGN_ID,
  SABA_API_KEY
} = process.env

export const getConfig = (campaign) => {
  const config = {
    SUPERLIKERS_URL,
    VERYFI_VALIDATE_URL,
    VERYFI_BASE_URL
  }

  if (campaign === 'sz') {
    config.VERYFI_CLIENT_ID = TENA_VERYFI_CLIENT_ID
    config.VERYFI_CLIENT_SECRET = TENA_VERYFI_CLIENT_SECRET
    config.VERIFY_API_KEY = TENA_VERIFY_API_KEY
    config.CAMPAIGN_ID = TENA_CAMPAIGN_ID
    config.VERYFI_USERNAME = TENA_VERYFI_USERNAME
    config.API_KEY = TENA_API_KEY
  }

  if (campaign === 'ua') {
    config.VERIFY_CLIENT_ID = SABA_VERIFY_CLIENT_ID
    config.VERIFY_CLIENT_SECRET = SABA_VERIFY_CLIENT_SECRET
    config.VERIFY_API_KEY = SABA_VERIFY_API_KEY
    config.CAMPAIGN_ID = SABA_CAMPAIGN_ID
    config.VERIFY_USERNAME = SABA_VERIFY_USERNAME
    config.API_KEY = SABA_API_KEY
  }

  return config
}
